#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CREDENTIALS_DIR="$ROOT_DIR/release/credentials"
KEYSTORE_PATH="$CREDENTIALS_DIR/saient-upload.jks"
PROPERTIES_PATH="$CREDENTIALS_DIR/keystore.properties"
ALIAS="saient-upload"

if [[ -e "$KEYSTORE_PATH" || -e "$PROPERTIES_PATH" ]]; then
  echo "Refusing to overwrite existing Android signing credentials in $CREDENTIALS_DIR" >&2
  exit 2
fi
if ! command -v keytool >/dev/null 2>&1; then
  echo "keytool is required to initialize Android signing." >&2
  exit 3
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate signing passwords." >&2
  exit 3
fi

umask 077
mkdir -p "$CREDENTIALS_DIR"
store_password="$(openssl rand -hex 32)"
key_password="$(openssl rand -hex 32)"

cleanup_partial() {
  if [[ ! -s "$PROPERTIES_PATH" ]]; then
    rm -f "$KEYSTORE_PATH" "$PROPERTIES_PATH"
  fi
}
trap cleanup_partial EXIT

keytool -genkeypair \
  -keystore "$KEYSTORE_PATH" \
  -storetype JKS \
  -storepass "$store_password" \
  -keypass "$key_password" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 4096 \
  -sigalg SHA256withRSA \
  -validity 10000 \
  -dname "CN=Saient Android Upload Key, O=Saient"

printf '%s\n' \
  "# Generated by npm run android:signing:init. Keep this file secret." \
  "storeFile=../release/credentials/saient-upload.jks" \
  "storePassword=$store_password" \
  "keyAlias=$ALIAS" \
  "keyPassword=$key_password" \
  > "$PROPERTIES_PATH"
chmod 600 "$KEYSTORE_PATH" "$PROPERTIES_PATH"
trap - EXIT

keytool -list \
  -keystore "$KEYSTORE_PATH" \
  -storepass "$store_password" \
  -alias "$ALIAS" \
  -v \
  | sed -n '/Alias name:/p;/Creation date:/p;/Entry type:/p;/Owner:/p;/Valid from:/p;/Certificate fingerprints:/,/Signature algorithm name:/p'

printf 'Created Android upload credentials in %s\n' "$CREDENTIALS_DIR"
printf 'Back up saient-upload.jks and keystore.properties together before the first Play upload.\n'
